export enum GameboardActions {
	TOGGLE_CARD_VISIBILITY = 'TOGGLE_CARD_VISIBILITY',
	RESET_CARDS = 'RESET_CARDS',
	LOCK_CARDS = 'LOCK_CARDS',
	SET_FIRST_CARD = 'SET_FIRST_CARD',
	INCREMENT_CARDS_FLIPPED = 'INCREMENT_CARDS_FLIPPED',
}
